const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const menuBtn=$("#menuBtn"),navLinks=$("#navLinks"),header=$("#header"),progress=$("#scrollProgress");
menuBtn?.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open));menuBtn.textContent=open?"×":"☰"});
$$(".nav-links a").forEach(a=>a.addEventListener("click",()=>{navLinks.classList.remove("open");menuBtn.setAttribute("aria-expanded","false");menuBtn.textContent="☰"}));
function scrollUI(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=max?(scrollY/max*100)+"%":"0%";header.classList.toggle("scrolled",scrollY>12)}addEventListener("scroll",scrollUI,{passive:true});scrollUI();
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});$$(".reveal").forEach(x=>observer.observe(x));
const sectionObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){$$(".nav-links a").forEach(a=>a.classList.remove("active"));$(`.nav-links a[href="#${e.target.id}"]`)?.classList.add("active")}}),{rootMargin:"-45% 0px -45% 0px"});$$("section[id]").forEach(s=>sectionObserver.observe(s));
const cursor=$(".cursor-glow");if(cursor&&matchMedia("(pointer:fine)").matches)addEventListener("pointermove",e=>{cursor.style.left=e.clientX+"px";cursor.style.top=e.clientY+"px"},{passive:true});else cursor?.remove();
const terminal=$("#terminalCard");if(terminal&&matchMedia("(pointer:fine)").matches){terminal.addEventListener("pointermove",e=>{const r=terminal.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;terminal.style.transform=`perspective(900px) rotateX(${((y/r.height)-.5)*-5}deg) rotateY(${((x/r.width)-.5)*6}deg) translateY(-5px)`});terminal.addEventListener("pointerleave",()=>terminal.style.transform="rotate(2.5deg)")}
const projects={
nuvora:{type:"FULL STACK",title:"Nuvora School Platform",description:"A multi-tenant school operations platform covering admissions, student records, academics, assessments, finance, communication and role-based access. The repository contains a React/Vite client and an Express/Prisma API backed by PostgreSQL.",stack:["React","Express","Prisma","PostgreSQL","JWT","RBAC"],github:"https://github.com/Michael-aal/petra-school-project"},
jarvis:{type:"PYTHON / AI",title:"Jarvis — App & Browser Control Engine",description:"A Python automation engine that parses structured intents and maps them to desktop actions such as opening applications, opening URLs, taking screenshots and querying device information.",stack:["Python","Automation","Intent Parsing","TTS","psutil"],github:"https://github.com/Michael-aal/my_ai"},
"petra-ai":{type:"WEB APP",title:"School AI Dashboard",description:"An Express-based school dashboard combining AI chat, activity management, announcements, school information and persistent chat history.",stack:["Node.js","Express","SQLite","Vanilla JS","OpenRouter"],github:"https://github.com/Michael-aal/petra-ai-dashboard"},
apology:{type:"WEB",title:"Apology Website",description:"A focused standalone web experience built around interaction, presentation and a clear message.",stack:["HTML","CSS","JavaScript"],github:"https://github.com/Michael-aal/apology-website"},
converter:{type:"UTILITY",title:"Unit Converter",description:"A compact utility project focused on conversion logic, straightforward interaction and responsive presentation.",stack:["JavaScript","HTML","CSS"],github:"https://github.com/Michael-aal/unit-converter"},
"living-bells":{type:"IN PROGRESS",title:"Living Bells",description:"A church activity and records platform for attendance, activities, finance records and staff review workflows. It is intentionally marked as in progress rather than presented as finished work.",stack:["React","Node.js","Prisma"],github:"https://github.com/Michael-aal/living-bells"}};
const modal=$("#projectModal"),title=$("#modalTitle"),type=$("#modalType"),description=$("#modalDescription"),stack=$("#modalStack"),github=$("#modalGithub");
function openProject(key){const p=projects[key];if(!p)return;type.textContent=p.type;title.textContent=p.title;description.textContent=p.description;stack.innerHTML=p.stack.map(x=>`<span>${x}</span>`).join("");github.href=p.github;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeProject(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
$$(".project-card").forEach(c=>c.addEventListener("click",()=>openProject(c.dataset.project)));
$$("[data-close-modal]").forEach(x=>x.addEventListener("click",closeProject));addEventListener("keydown",e=>{if(e.key==="Escape")closeProject()});
$("#year").textContent=new Date().getFullYear();